import datetime

debug = False

# Probability of a Lead advancing to the next stage
leadToQualifySuccessRate = 0.2
qualifyToSolutionSuccessRate = 0.8
# SolutionToProposal rate is ML calculated
proposalToFinalizeSuccessRate = 0.9

# How much time passes between stage facts
leadStartDate = datetime.date(2018, 1, 1)
leadEndDate = datetime.date(2019, 12, 31)
leadToQualifyDelta = (20, 5)  # (Average, Deviation)
qualifyToSolutionDelta = (45, 10)
solutionToProposalDelta = (7, 2)
proposalToFinalizeDelta = (7, 5)
deltas = [
    leadToQualifyDelta,
    qualifyToSolutionDelta,
    solutionToProposalDelta,
    proposalToFinalizeDelta
]

# P2 Dev range
# Number of P1 devs dynamically generated by an account's gold ration
p2_dev_range = {
    "small": (1, 5),
    "medium": (5, 10),
    "large": (10, 40)
}
